SKILL_CATEGORIES = {
    "frontend": [
        "javascript",
        "typescript",
        "react",
        "vue",
        "angular",
        "html",
        "css",
        "tailwind",
        "next.js",
        "nextjs",
        "svelte",
        "webpack",
        "redux",
        "vue.js",
        "angularjs",
        "jquery",
        "sass",
        "scss",
        "less",
        "bootstrap",
        "material-ui",
        "mui",
        "styled-components",
        "emotion",
        "storybook",
        "jest",
        "vitest",
        "cypress",
        "playwright",
        "webdriver",
        "responsive design",
        "accessibility",
        "a11y",
        "pwa",
        "progressive web app",
        "webpack",
        "vite",
        "esbuild",
        "rollup",
        "parcel",
    ],
    "backend": [
        "python",
        "django",
        "flask",
        "fastapi",
        "java",
        "spring",
        "spring boot",
        "c#",
        ".net",
        "node",
        "node.js",
        "nodejs",
        "express",
        "go",
        "golang",
        "ruby",
        "rails",
        "c++",
        "cpp",
        "c",
        "rust",
        "swift",
        "kotlin",
        "php",
        "scala",
        "graphql",
        "rest api",
        "rest",
        "api",
        "microservices",
        "serverless",
        "gin",
        "echo",
        "fiber",
        "actix",
        "rocket",
        "sinatra",
        "tornado",
        "aiohttp",
        "asyncio",
        "celery",
        "rq",
        "grpc",
        "websocket",
        "socket.io",
        "message queue",
        "rabbitmq",
        "activemq",
        "apache kafka",
        "kafka",
    ],
    "fullstack": [
        "full stack",
        "full-stack",
        "fullstack",
    ],
    "data": [
        "sql",
        "postgresql",
        "mysql",
        "mongodb",
        "pandas",
        "numpy",
        "data engineer",
        "data scientist",
        "data science",
        "spark",
        "redis",
        "elasticsearch",
        "cassandra",
        "dynamodb",
        "nosql",
        "data warehouse",
        "etl",
        "airflow",
        "kafka",
        "hadoop",
        "hive",
        "presto",
        "trino",
        "clickhouse",
        "snowflake",
        "bigquery",
        "redshift",
        "databricks",
        "dbt",
        "tableau",
        "power bi",
        "looker",
        "superset",
        "metabase",
        "sqlite",
        "oracle",
        "sql server",
        "mariadb",
        "couchdb",
        "neo4j",
        "influxdb",
        "timescaledb",
        "data modeling",
        "data pipeline",
        "data lake",
    ],
    "ml_ai": [
        "machine learning",
        "deep learning",
        "pytorch",
        "tensorflow",
        "scikit-learn",
        "sklearn",
        "ml engineer",
        "ai engineer",
        "llm",
        "large language model",
        "transformer",
        "neural network",
        "nlp",
        "natural language processing",
        "computer vision",
        "reinforcement learning",
        "gpu",
        "cuda",
        "keras",
        "jax",
        "hugging face",
        "transformers",
        "openai",
        "langchain",
        "llama",
        "gpt",
        "bert",
        "lstm",
        "cnn",
        "rnn",
        "gan",
        "svm",
        "random forest",
        "xgboost",
        "lightgbm",
        "catboost",
        "feature engineering",
        "model deployment",
        "mlops",
        "model serving",
        "triton",
        "onnx",
        "tensorrt",
        "opencv",
        "nltk",
        "spacy",
        "gensim",
        "prompt engineering",
    ],
    "security": [
        "security engineer",
        "application security",
        "appsec",
        "infosec",
        "information security",
        "soc",
        "siem",
        "threat detection",
        "incident response",
        "penetration testing",
        "pentest",
        "vulnerability management",
        "devsecops",
        "owasp",
        "cryptography",
        "encryption",
        "authentication",
        "authorization",
        "oauth",
        "jwt",
        "saml",
        "ldap",
        "rbac",
        "zero trust",
        "firewall",
        "ids",
        "ips",
        "waf",
        "dns security",
        "ssl",
        "tls",
        "certificate management",
        "secrets management",
        "vault",
        "hashiCorp vault",
        "burp suite",
        "metasploit",
        "nmap",
        "wireshark",
        "security audit",
        "compliance",
        "gdpr",
        "hipaa",
        "pci dss",
        "iso 27001",
    ],
    "devops": [
        "aws",
        "azure",
        "gcp",
        "docker",
        "kubernetes",
        "terraform",
        "ci/cd",
        "lambda",
        "s3",
        "ec2",
        "jenkins",
        "github actions",
        "gitlab ci",
        "ansible",
        "chef",
        "puppet",
        "prometheus",
        "grafana",
        "linux",
        "unix",
        "bash",
        "shell scripting",
        "git",
        "helm",
        "istio",
        "linkerd",
        "argo",
        "flux",
        "spinnaker",
        "circleci",
        "travis ci",
        "bamboo",
        "teamcity",
        "cloudformation",
        "pulumi",
        "packer",
        "vagrant",
        "consul",
        "nomad",
        "vault",
        "nginx",
        "apache",
        "haproxy",
        "kong",
        "envoy",
        "datadog",
        "new relic",
        "splunk",
        "elk stack",
        "elastic stack",
        "loki",
        "jaeger",
        "zipkin",
        "monitoring",
        "observability",
        "apm",
        "distributed tracing",
    ],
    "systems": [
        "multithreading",
        "concurrency",
        "parallel computing",
        "distributed systems",
        "operating systems",
        "system design",
        "performance optimization",
        "memory management",
        "cpu optimization",
        "cache",
        "caching",
        "load balancing",
        "scalability",
        "high availability",
        "fault tolerance",
        "disaster recovery",
        "backup",
        "replication",
        "sharding",
        "partitioning",
        "consensus algorithms",
        "raft",
        "paxos",
        "event sourcing",
        "cqrs",
        "message broker",
        "queue",
        "pub/sub",
        "stream processing",
    ],
}


# For now, we treat all of the above skills as the keyword universe we care about.
KEYWORD_SKILLS = sorted(
    {skill.lower() for skills in SKILL_CATEGORIES.values() for skill in skills}
)


# GitHub API configuration
GITHUB_API_BASE = "https://api.github.com"
GITHUB_GRAPHQL_ENDPOINT = "https://api.github.com/graphql"
RATE_LIMIT_REQUESTS_PER_HOUR = 5000  # Authenticated limit

# Issue search labels
GOOD_FIRST_ISSUE_LABELS = ["good first issue", "good-first-issue", "beginner-friendly", "beginner friendly"]
HELP_WANTED_LABELS = ["help wanted", "help-wanted"]

# Scoring weights
SKILL_MATCH_WEIGHT = 40
EXPERIENCE_MATCH_WEIGHT = 20
REPO_QUALITY_WEIGHT = 15
FRESHNESS_WEIGHT = 10
TIME_MATCH_WEIGHT = 10
INTEREST_MATCH_WEIGHT = 5

